import { AuthorInfo, StoryInfo } from './types';

export const authors: AuthorInfo[] = [
    {
        id: 1,
        authorName: 'Sophia Carter',
        authorImgSrc: '/images/authors/sophia.jpg',
        noOfStories: 12,
        noOfFollowers: 2340,
        tags: ['fiction', 'romance', 'drama'],
    },
    {
        id: 2,
        authorName: 'Liam Jackson',
        authorImgSrc: '/images/authors/liam.jpg',
        noOfStories: 8,
        noOfFollowers: 1875,
        tags: ['thriller', 'mystery'],
    },
    {
        id: 3,
        authorName: 'Emily Zhang',
        authorImgSrc: '/images/authors/emily.jpg',
        noOfStories: 15,
        noOfFollowers: 3200,
        tags: ['fantasy', 'adventure', 'young adult'],
    },
    {
        id: 4,
        authorName: 'Noah Thompson',
        authorImgSrc: '/images/authors/noah.jpg',
        noOfStories: 10,
        noOfFollowers: 2045,
        tags: ['sci-fi', 'dystopian'],
    },
    {
        id: 5,
        authorName: 'Ava Mitchell',
        authorImgSrc: '/images/authors/ava.jpg',
        noOfStories: 5,
        noOfFollowers: 990,
        tags: ['poetry', 'life'],
    },
    {
        id: 6,
        authorName: 'James Rivera',
        authorImgSrc: '/images/authors/james.jpg',
        noOfStories: 20,
        noOfFollowers: 4100,
        tags: ['historical', 'biography'],
    },
    {
        id: 7,
        authorName: 'Isabella Chen',
        authorImgSrc: '/images/authors/isabella.jpg',
        noOfStories: 7,
        noOfFollowers: 1320,
        tags: ['romance', 'contemporary'],
    },
    {
        id: 8,
        authorName: 'Ethan Patel',
        authorImgSrc: '/images/authors/ethan.jpg',
        noOfStories: 9,
        noOfFollowers: 1450,
        tags: ['tech', 'sci-fi', 'non-fiction'],
    },
    {
        id: 9,
        authorName: 'Mia Robinson',
        authorImgSrc: '/images/authors/mia.jpg',
        noOfStories: 14,
        noOfFollowers: 2780,
        tags: ['mystery', 'psychological'],
    },
    {
        id: 10,
        authorName: 'William Kim',
        authorImgSrc: '/images/authors/william.jpg',
        noOfStories: 6,
        noOfFollowers: 1130,
        tags: ['horror', 'suspense'],
    },
];

export const stories: StoryInfo[] = [
    {
        id: 1,
        title: 'Whispers in the Wind',
        author: authors[0],
        imgSrc: '/images/stories/story_1.jpg',
        tags: ['romance', 'drama'],
        isBookmarked: true,
        description:
            'A captivating tale of mystery and love that unravels in the most unexpected way.',
        isEditorsPick: true,
    },
    {
        id: 2,
        title: 'Shadow Over the Valley',
        author: authors[1],
        imgSrc: '/images/stories/story_2.jpg',
        tags: ['thriller', 'mystery'],
        isBookmarked: false,
        description: 'A powerful narrative about facing the past and seeking redemption.',
        isEditorsPick: false,
    },
    {
        id: 3,
        title: 'Echoes of the Past',
        author: authors[2],
        imgSrc: '/images/stories/story_3.jpg',
        tags: ['fantasy', 'adventure'],
        isBookmarked: true,
        description: 'Follow the journey of a soul torn between two worlds.',
        isEditorsPick: true,
    },
    {
        id: 4,
        title: 'The Lost Heir',
        author: authors[3],
        imgSrc: '/images/stories/story_4.jpg',
        tags: ['sci-fi', 'dystopian'],
        isBookmarked: false,
        description: 'An epic fantasy filled with magic, betrayal, and a fight for the throne.',
        isEditorsPick: false,
    },
    {
        id: 5,
        title: 'Dreamwalker',
        author: authors[4],
        imgSrc: '/images/stories/story_5.jpg',
        tags: ['poetry', 'life'],
        isBookmarked: false,
        description: 'Dive into a dystopian future where truth is the greatest weapon.',
        isEditorsPick: true,
    },
    {
        id: 6,
        title: 'Twilight Hunt',
        author: authors[5],
        imgSrc: '/images/stories/story_6.jpg',
        tags: ['historical', 'thriller'],
        isBookmarked: true,
        description: 'A quiet town hides dark secrets in this chilling psychological thriller.',
        isEditorsPick: false,
    },
    {
        id: 7,
        title: 'Voices Beneath',
        author: authors[6],
        imgSrc: '/images/stories/story_7.jpg',
        tags: ['romance', 'contemporary'],
        isBookmarked: false,
        description: 'Adventure, loyalty, and heartbreak await in this gripping saga.',
        isEditorsPick: true,
    },
    {
        id: 8,
        title: 'Fragments of Tomorrow',
        author: authors[7],
        imgSrc: '/images/stories/story_8.jpg',
        tags: ['tech', 'sci-fi'],
        isBookmarked: true,
        description: 'Explore the hidden history buried beneath centuries of lies.',
        isEditorsPick: false,
    },
    {
        id: 9,
        title: 'Cursed Legacy',
        author: authors[8],
        imgSrc: '/images/stories/story_9.jpg',
        tags: ['mystery', 'psychological'],
        isBookmarked: false,
        description: 'A science fiction adventure that bends the limits of reality.',
        isEditorsPick: true,
    },
    {
        id: 10,
        title: 'Midnight Bloom',
        author: authors[9],
        imgSrc: '/images/stories/story_10.jpg',
        tags: ['horror', 'suspense'],
        isBookmarked: true,
        description: 'Where dreams and nightmares collide, a story begins.',
        isEditorsPick: false,
    },

    // Repeating structure with variation
    {
        id: 11,
        title: 'Tides of Fate',
        author: authors[0],
        imgSrc: '/images/stories/story_11.jpg',
        tags: ['fiction', 'romance'],
        isBookmarked: false,
        description: 'An emotional journey through love, loss, and destiny.',
        isEditorsPick: true,
    },
    {
        id: 12,
        title: 'Ashes and Embers',
        author: authors[1],
        imgSrc: '/images/stories/story_12.jpg',
        tags: ['thriller', 'drama'],
        isBookmarked: true,
        description: 'Dark secrets and betrayal rise from the ashes.',
        isEditorsPick: false,
    },
    {
        id: 13,
        title: 'The Last Light',
        author: authors[2],
        imgSrc: '/images/stories/story_13.jpg',
        tags: ['fantasy', 'young adult'],
        isBookmarked: true,
        description: 'One final battle will determine the fate of the realms.',
        isEditorsPick: true,
    },
    {
        id: 14,
        title: 'Secrets Unfold',
        author: authors[3],
        imgSrc: '/images/stories/story_14.jpg',
        tags: ['sci-fi', 'adventure'],
        isBookmarked: false,
        description: 'An exploration crew uncovers ancient alien technology.',
        isEditorsPick: false,
    },
    {
        id: 15,
        title: 'Beyond the Mist',
        author: authors[4],
        imgSrc: '/images/stories/story_15.jpg',
        tags: ['life', 'poetry'],
        isBookmarked: true,
        description: 'A lyrical journey through healing and self-discovery.',
        isEditorsPick: false,
    },
    {
        id: 16,
        title: 'Path of Thorns',
        author: authors[5],
        imgSrc: '/images/stories/story_16.jpg',
        tags: ['biography', 'drama'],
        isBookmarked: false,
        description: 'The untold story of a revolution and its sacrifices.',
        isEditorsPick: true,
    },
    {
        id: 17,
        title: 'Memory of Fire',
        author: authors[6],
        imgSrc: '/images/stories/story_17.jpg',
        tags: ['romance', 'thriller'],
        isBookmarked: true,
        description: 'She remembers everything—except who to trust.',
        isEditorsPick: true,
    },
    {
        id: 18,
        title: 'Frostbite Heart',
        author: authors[7],
        imgSrc: '/images/stories/story_18.jpg',
        tags: ['sci-fi', 'non-fiction'],
        isBookmarked: false,
        description: 'A story of survival in a frozen future.',
        isEditorsPick: false,
    },
    {
        id: 19,
        title: 'The Veil',
        author: authors[8],
        imgSrc: '/images/stories/story_19.jpg',
        tags: ['psychological', 'mystery'],
        isBookmarked: true,
        description: 'What’s hidden behind the veil may change everything.',
        isEditorsPick: false,
    },
    {
        id: 20,
        title: 'Sunset Chronicles',
        author: authors[9],
        imgSrc: '/images/stories/story_20.jpg',
        tags: ['suspense', 'horror'],
        isBookmarked: false,
        description: 'A serial killer leaves clues in the shadows of dusk.',
        isEditorsPick: true,
    },

    // Final 10
    {
        id: 21,
        title: 'Dust and Gold',
        author: authors[1],
        imgSrc: '/images/stories/story_21.jpg',
        tags: ['historical', 'adventure'],
        isBookmarked: false,
        description: 'Gold rush greed and justice in the wild frontier.',
        isEditorsPick: false,
    },
    {
        id: 22,
        title: 'Iron Will',
        author: authors[3],
        imgSrc: '/images/stories/story_22.jpg',
        tags: ['dystopian', 'action'],
        isBookmarked: true,
        description: 'When the world breaks, only the strong survive.',
        isEditorsPick: true,
    },
    {
        id: 23,
        title: "The Serpent's Mark",
        author: authors[6],
        imgSrc: '/images/stories/story_23.jpg',
        tags: ['fantasy', 'mystery'],
        isBookmarked: false,
        description: 'A sacred curse haunts generations of royalty.',
        isEditorsPick: false,
    },
    {
        id: 24,
        title: 'A Distant Shore',
        author: authors[2],
        imgSrc: '/images/stories/story_24.jpg',
        tags: ['romance', 'drama'],
        isBookmarked: true,
        description: 'Two souls meet in a foreign land and rewrite fate.',
        isEditorsPick: true,
    },
    {
        id: 25,
        title: 'Lantern in the Dark',
        author: authors[0],
        imgSrc: '/images/stories/story_25.jpg',
        tags: ['mystery', 'adventure'],
        isBookmarked: false,
        description: 'A child’s lantern becomes the key to a hidden truth.',
        isEditorsPick: true,
    },
    {
        id: 26,
        title: 'The Forbidden Script',
        author: authors[8],
        imgSrc: '/images/stories/story_26.jpg',
        tags: ['psychological', 'thriller'],
        isBookmarked: true,
        description: 'A writer discovers a story that shouldn’t exist.',
        isEditorsPick: false,
    },
    {
        id: 27,
        title: 'Chains of Glass',
        author: authors[5],
        imgSrc: '/images/stories/story_27.jpg',
        tags: ['biography', 'suspense'],
        isBookmarked: false,
        description: 'One woman’s journey through injustice and power.',
        isEditorsPick: true,
    },
    {
        id: 28,
        title: 'Dawn of Silence',
        author: authors[7],
        imgSrc: '/images/stories/story_28.jpg',
        tags: ['tech', 'sci-fi'],
        isBookmarked: true,
        description: 'Silence is law in a society ruled by algorithms.',
        isEditorsPick: false,
    },
    {
        id: 29,
        title: 'Vortex Rising',
        author: authors[3],
        imgSrc: '/images/stories/story_29.jpg',
        tags: ['sci-fi', 'dystopian'],
        isBookmarked: true,
        description: "A rogue pilot holds the key to Earth's survival.",
        isEditorsPick: true,
    },
    {
        id: 30,
        title: "The Clockmaker's Paradox",
        author: authors[9],
        imgSrc: '/images/stories/story_30.jpg',
        tags: ['fantasy', 'time travel'],
        isBookmarked: false,
        description: 'A time-traveling inventor unravels his own fate.',
        isEditorsPick: false,
    },
];

export const categories = [
    {
        categoryName: 'Fantasy',
        noOfStories: 153,
        categoryImgSrc: 'img/fantasy.jpg',
    },
    {
        categoryName: 'Romance',
        noOfStories: 124,
        categoryImgSrc: 'img/romance.jpg',
    },
    {
        categoryName: 'Drama',
        noOfStories: 232,
        categoryImgSrc: 'img/drama.jpg',
    },
    {
        categoryName: 'Horror',
        noOfStories: 93,
        categoryImgSrc: 'img/horror.jpg',
    },
    {
        categoryName: 'Science Fiction',
        noOfStories: 145,
        categoryImgSrc: 'img/sci-fi.jpg',
    },
    {
        categoryName: 'Thriller',
        noOfStories: 276,
        categoryImgSrc: 'img/thriller.jpg',
    },
    {
        categoryName: 'Cyberpunk',
        noOfStories: 86,
        categoryImgSrc: 'img/cyberpunk.jpg',
    },
    {
        categoryName: 'History',
        noOfStories: 99,
        categoryImgSrc: 'img/history.jpg',
    },
];
